---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstagetry
  docu: https://wiki.ehealthinsurance.com/display/BEAS/Architecture+Design+for+Notification+Service
  annotations:
    github.com/project-slug: ealparslan/backstagetry
    jenkins.io/github-folder: APPF/APPF-plan-service
spec:
  type: service
  lifecycle: production
  owner: team-a
